name: CI Workflow

# 실행 조건
on:
  push:
    branches:
      - "dev"

# 수행할 작업 설정
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: JDK 17 설정
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Gradle Wrapper 실행 권한 부여
        run: chmod +x ./gradlew
      - name: 빌드 및 테스트
        run: ./gradlew clean build